/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Conexion;
import Controlador.CuerpoDeAguaControler;
import Dao.CuerpoDeAguaDAO;
import Modelo.CuerpoDeAgua;
import Modelo.DensidadPoblacional;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author Gregory
 */
public class Formulario extends javax.swing.JFrame {
    //Definición del modelo
    DefaultListModel modelo = new DefaultListModel();
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        crearModelo();
    }
    //Llenado en ejecución del modelo
    private void crearModelo(){
        lstlista.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txtidcuerpodeagua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmunicipio = new javax.swing.JTextField();
        txttipodecuerpodeagua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttipodeagua = new javax.swing.JTextField();
        txtirca = new javax.swing.JTextField();
        btningresar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdatosingresados = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtsalidas = new javax.swing.JTextArea();
        btnobtener = new javax.swing.JButton();
        btnprocesar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtnombre1 = new javax.swing.JTextField();
        txtidcuerpodeagua1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmunicipio1 = new javax.swing.JTextField();
        txttipodecuerpodeagua1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttipodeagua1 = new javax.swing.JTextField();
        txtbusqueda = new javax.swing.JTextField();
        btningresar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtirca1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btningresar2 = new javax.swing.JButton();
        btningresar3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstlista = new javax.swing.JList<>();
        btnobtener1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtafeccion = new javax.swing.JTextField();
        btnafeccion = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad del Norte - Grupo 1866 - Grégory García Cabrera - Reto 5");
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Chiller", 0, 10)); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel3.setText("Municipio");

        jLabel4.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel4.setText("Tipo de cuerpo de agua");

        jLabel5.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de agua");

        jLabel6.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel6.setText("IRCA");

        btningresar.setBackground(new java.awt.Color(0, 0, 255));
        btningresar.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btningresar.setForeground(new java.awt.Color(255, 255, 255));
        btningresar.setText("Ingresar");
        btningresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reto4/Images/irca_logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtidcuerpodeagua, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(txtmunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(txttipodeagua))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtirca, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttipodecuerpodeagua, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(239, 239, 239))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btningresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidcuerpodeagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttipodecuerpodeagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtirca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttipodeagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btningresar)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar", jPanel1);

        jLabel8.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 14)); // NOI18N
        jLabel8.setText("Salidas");

        txtdatosingresados.setColumns(20);
        txtdatosingresados.setRows(5);
        jScrollPane1.setViewportView(txtdatosingresados);

        jLabel7.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 14)); // NOI18N
        jLabel7.setText("Datos ingresados");

        txtsalidas.setColumns(20);
        txtsalidas.setRows(5);
        jScrollPane2.setViewportView(txtsalidas);

        btnobtener.setBackground(new java.awt.Color(0, 0, 255));
        btnobtener.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnobtener.setForeground(new java.awt.Color(255, 255, 255));
        btnobtener.setText("Obtener datos");
        btnobtener.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnobtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnobtenerActionPerformed(evt);
            }
        });

        btnprocesar.setBackground(new java.awt.Color(0, 0, 255));
        btnprocesar.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnprocesar.setForeground(new java.awt.Color(255, 255, 255));
        btnprocesar.setText("Procesar datos");
        btnprocesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprocesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnobtener)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnprocesar))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel7)
                        .addGap(254, 254, 254)
                        .addComponent(jLabel8)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnobtener)
                    .addComponent(btnprocesar))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Procesar datos", jPanel2);

        txtnombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombre1ActionPerformed(evt);
            }
        });

        txtidcuerpodeagua1.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel10.setText("Id");

        jLabel11.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel11.setText("Municipio");

        jLabel12.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel12.setText("Tipo de cuerpo de agua");

        jLabel13.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel13.setText("Tipo de agua");

        jLabel14.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel14.setText("IRCA");

        btningresar1.setBackground(new java.awt.Color(0, 0, 255));
        btningresar1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btningresar1.setForeground(new java.awt.Color(255, 255, 255));
        btningresar1.setText("Editar");
        btningresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btningresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel15.setText("ID");

        btningresar2.setBackground(new java.awt.Color(0, 0, 255));
        btningresar2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btningresar2.setForeground(new java.awt.Color(255, 255, 255));
        btningresar2.setText("Buscar");
        btningresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btningresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar2ActionPerformed(evt);
            }
        });

        btningresar3.setBackground(new java.awt.Color(0, 0, 255));
        btningresar3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btningresar3.setForeground(new java.awt.Color(255, 255, 255));
        btningresar3.setText("Eliminar");
        btningresar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btningresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txttipodeagua1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtirca1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtmunicipio1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(txtidcuerpodeagua1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(txttipodecuerpodeagua1)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btningresar1)
                                .addGap(71, 71, 71)
                                .addComponent(btningresar3))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btningresar2)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btningresar2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)
                                .addGap(4, 4, 4)
                                .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidcuerpodeagua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtmunicipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttipodecuerpodeagua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttipodeagua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtirca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningresar1)
                    .addComponent(btningresar3))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 203, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar / Eliminar", jPanel3);

        jScrollPane3.setViewportView(lstlista);

        btnobtener1.setBackground(new java.awt.Color(0, 0, 255));
        btnobtener1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnobtener1.setForeground(new java.awt.Color(255, 255, 255));
        btnobtener1.setText("Obtener datos");
        btnobtener1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnobtener1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnobtener1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Uso de JList");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnobtener1)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel17)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnobtener1)
                    .addComponent(jLabel17))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Obtener Datos", jPanel5);

        btnafeccion.setBackground(new java.awt.Color(0, 0, 255));
        btnafeccion.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        btnafeccion.setForeground(new java.awt.Color(255, 255, 255));
        btnafeccion.setText("Indice de affección");
        btnafeccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnafeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnafeccionActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Exotc350 Bd BT", 0, 12)); // NOI18N
        jLabel18.setText("Ingrese el número de habitantes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel18)
                .addGap(31, 31, 31)
                .addComponent(txtafeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnafeccion)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtafeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(btnafeccion))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Densidad Poblacional", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        CuerpoDeAgua cuerpo = new CuerpoDeAgua();
        CuerpoDeAguaDAO cuerpodao = new CuerpoDeAguaDAO();
        
        CuerpoDeAguaControler controler = new CuerpoDeAguaControler();
        cuerpo.setNombre(txtnombre.getText());
        cuerpo.setId_cuerpo_agua(Integer.parseInt(txtidcuerpodeagua.getText()));
        cuerpo.setMunicipio(txtmunicipio.getText());
        cuerpo.setTipocuerpodeagua(txttipodecuerpodeagua.getText());
        cuerpo.setTipodeagua(txttipodeagua.getText());
        cuerpo.setIrca(Double.parseDouble(txtirca.getText()));
        
        if(controler.guardar(cuerpo)){
            JOptionPane.showMessageDialog(null, "Cuerpo de agua guardado");
        }
        else{
            JOptionPane.showMessageDialog(null, "Cuerpo de agua NO guardado");
        }
        
    }//GEN-LAST:event_btningresarActionPerformed

    private void btnobtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnobtenerActionPerformed
        
        ArrayList<CuerpoDeAgua> bcuerpo = new ArrayList<>();
        ResultSet rs;        
        txtdatosingresados.setText("");
        Connection con = Conexion.conectar();
        //Consultar en la base de datos
        String sql = "select * from CuerpoDeAgua";        
        
        try {
            PreparedStatement ps = con.prepareStatement(sql);            
            
            rs = ps.executeQuery();
            while(rs.next()){
                
                CuerpoDeAgua cuerpo = new CuerpoDeAgua();                
                cuerpo.setNombre(rs.getString("nombre"));
                cuerpo.setId_cuerpo_agua(rs.getInt("id"));
                cuerpo.setMunicipio(rs.getString("municipio"));
                cuerpo.setTipocuerpodeagua(rs.getString("tipodecuerpodeagua"));
                cuerpo.setTipodeagua(rs.getString("tipodeagua"));
                cuerpo.setIrca(rs.getDouble("clasificacionirca"));
                                
                bcuerpo.add(cuerpo);
            
            }
        
        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
        try {
            con.close();
            
        }
        catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        for (CuerpoDeAgua cuerpoDeAgua : bcuerpo) {
            txtdatosingresados.setText(txtdatosingresados.getText()+cuerpoDeAgua.getNombre()+" "+cuerpoDeAgua.getId_cuerpo_agua()+" "+cuerpoDeAgua.getMunicipio()+" "+cuerpoDeAgua.getTipocuerpodeagua()+" "+cuerpoDeAgua.getTipodeagua()+" "+cuerpoDeAgua.getIrca()+"\n");
        }
    }//GEN-LAST:event_btnobtenerActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre1ActionPerformed

    private void btningresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar1ActionPerformed
        CuerpoDeAguaControler controler = new CuerpoDeAguaControler();
        
        
        CuerpoDeAgua cuerpo = new CuerpoDeAgua();
        cuerpo.setNombre(txtnombre1.getText());
        cuerpo.setId_cuerpo_agua(Integer.parseInt(txtidcuerpodeagua1.getText()));
        cuerpo.setMunicipio(txtmunicipio1.getText());
        cuerpo.setTipocuerpodeagua(txttipodecuerpodeagua1.getText());
        cuerpo.setTipodeagua(txttipodeagua1.getText());
        cuerpo.setIrca(Double.parseDouble(txtirca1.getText()));
        
        if(controler.editar(cuerpo)){
            JOptionPane.showMessageDialog(null, "Cuerpo de agua actualizado correctamente");
        }
        else{
            JOptionPane.showMessageDialog(null, "Cuerpo de agua NO editado");
        }
        
    }//GEN-LAST:event_btningresar1ActionPerformed

    private void btningresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar2ActionPerformed
        CuerpoDeAgua cuerpo = new CuerpoDeAgua();
        CuerpoDeAguaControler controler = new CuerpoDeAguaControler();
        if(controler.buscar(cuerpo, Integer.parseInt(txtbusqueda.getText()))){
            JOptionPane.showMessageDialog(null, "Registro encontrado");
            txtnombre1.setText(cuerpo.getNombre());
            txtidcuerpodeagua1.setText(String.valueOf(cuerpo.getId_cuerpo_agua()));
            txtmunicipio1.setText(cuerpo.getMunicipio());
            txttipodecuerpodeagua1.setText(cuerpo.getTipocuerpodeagua());
            txttipodeagua1.setText(cuerpo.getTipodeagua());
            txtirca1.setText(String.valueOf(cuerpo.getIrca()));
        }
        else{
            JOptionPane.showMessageDialog(null, "ID No encontrado");
            txtbusqueda.setText("");
            txtnombre1.setText("");
            txtidcuerpodeagua1.setText("");
            txtmunicipio1.setText("");
            txttipodecuerpodeagua1.setText("");
            txttipodeagua1.setText("");
            txtirca1.setText("");
        }  
        
    }//GEN-LAST:event_btningresar2ActionPerformed

    private void btningresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresar3ActionPerformed
        CuerpoDeAgua cuerpo = new CuerpoDeAgua();
        
        cuerpo.setId_cuerpo_agua(Integer.parseInt(txtidcuerpodeagua1.getText()));
        
        CuerpoDeAguaControler controler = new CuerpoDeAguaControler();
        
        if(controler.eliminar(cuerpo)){
            JOptionPane.showMessageDialog(null, "Cuerpo de agua eliminado correctamente");
        }
        else{
            JOptionPane.showMessageDialog(null, "Cuerpo de agua NO eliminado");
        }
        

    }//GEN-LAST:event_btningresar3ActionPerformed

    private void btnprocesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocesarActionPerformed
        txtsalidas.setText("");
        //Depurar datos
        String linea=txtdatosingresados.getText().strip();
        String vector[]=linea.split("\n");
        CuerpoDeAgua vectordatos[] = new CuerpoDeAgua[vector.length];
        for (int i = 0; i < vector.length; i++) {
            String temp[] = vector[i].split(" ");
            //Datos ingresados
            //String tipocuerpodeagua, String tipodeagua, float irca, String nombre, int id_cuerpo_agua, String municipio
            vectordatos[i]=new CuerpoDeAgua(temp[3], temp[4], Double.parseDouble(temp[5]), temp[0], Integer.parseInt(temp[1]),temp[2]);
            ////Datos esperados del problema
            //Nombre	Id      Municipio	Tipo cuerpo de agua	Tipo de agua	IRCA
        }
        String nivel;
        for (int i = 0; i < vector.length; i++) {
            nivel=vectordatos[i].nivel();
            
            txtsalidas.setText(txtsalidas.getText()+nivel+"\n");
        }
        txtsalidas.setText(txtsalidas.getText()+CuerpoDeAgua.getContador()+",00\n");
        int c = 0;
        String n1=null;
        for (int i = 0; i < vectordatos.length; i++) {            
            if(vectordatos[i].getIrca()>14 && vectordatos[i].getIrca()<=35){
                n1 = vectordatos[i].getNombre();                
                txtsalidas.setText(txtsalidas.getText()+n1+"\n");
                c++;
            } 
        } 
        if (c == 0) {
            System.out.println("NA");
            txtsalidas.setText(txtsalidas.getText()+"NA"+"\n");
        }
        
        double menor = 1000000000;
        String nombre_menor = "";
        int id_menor = 1000000000;
 
        for (int i = 0; i < vectordatos.length; i++) {
            if(vectordatos[i].getIrca()<menor){
                menor = vectordatos[i].getIrca();
                nombre_menor = vectordatos[i].getNombre();
                id_menor = vectordatos[i].getId_cuerpo_agua();
            }
        }
        txtsalidas.setText(txtsalidas.getText()+nombre_menor+" "+id_menor+",00\n");
            // TODO add your handling code here:
    }//GEN-LAST:event_btnprocesarActionPerformed

    private void btnobtener1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnobtener1ActionPerformed
        modelo.removeAllElements();
        ArrayList<CuerpoDeAgua> bcuerpo = new ArrayList<>();
        ResultSet rs;        
        txtdatosingresados.setText("");
        Connection con = Conexion.conectar();
        //Consultar en la base de datos
        String sql = "select * from CuerpoDeAgua";        
        
        try {
            PreparedStatement ps = con.prepareStatement(sql);            
            
            rs = ps.executeQuery();
            while(rs.next()){
                
                CuerpoDeAgua cuerpo = new CuerpoDeAgua();                
                cuerpo.setNombre(rs.getString("nombre"));
                cuerpo.setId_cuerpo_agua(rs.getInt("id"));
                cuerpo.setMunicipio(rs.getString("municipio"));
                cuerpo.setTipocuerpodeagua(rs.getString("tipodecuerpodeagua"));
                cuerpo.setTipodeagua(rs.getString("tipodeagua"));
                cuerpo.setIrca(rs.getDouble("clasificacionirca"));
                                
                bcuerpo.add(cuerpo);
            
            }
        
        } catch (SQLException e) {
            System.out.println(e.getMessage());

        }
        try {
            con.close();
            
        }
        catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        for (CuerpoDeAgua cuerpoDeAgua : bcuerpo) {
            modelo.addElement(cuerpoDeAgua.getNombre()+" "+cuerpoDeAgua.getId_cuerpo_agua()+" "+cuerpoDeAgua.getMunicipio()+" "+cuerpoDeAgua.getTipocuerpodeagua()+" "+cuerpoDeAgua.getTipodeagua()+" "+cuerpoDeAgua.getIrca()+"\n");
        }
    }//GEN-LAST:event_btnobtener1ActionPerformed

    private void btnafeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnafeccionActionPerformed
        DensidadPoblacional densidad = new DensidadPoblacional();
        densidad.setHabitantes(Integer.parseInt(txtafeccion.getText()));
        int rta = densidad.afeccion();
        JOptionPane.showMessageDialog(null, rta);
        
        
    }//GEN-LAST:event_btnafeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }/*
    class FondoPanel extends JPanel
    {
        private Image imagen;
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnafeccion;
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btningresar1;
    private javax.swing.JButton btningresar2;
    private javax.swing.JButton btningresar3;
    private javax.swing.JButton btnobtener;
    private javax.swing.JButton btnobtener1;
    private javax.swing.JButton btnprocesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lstlista;
    private javax.swing.JTextField txtafeccion;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextArea txtdatosingresados;
    public javax.swing.JTextField txtidcuerpodeagua;
    private javax.swing.JTextField txtidcuerpodeagua1;
    public javax.swing.JTextField txtirca;
    private javax.swing.JTextField txtirca1;
    public javax.swing.JTextField txtmunicipio;
    private javax.swing.JTextField txtmunicipio1;
    public javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextArea txtsalidas;
    public javax.swing.JTextField txttipodeagua;
    private javax.swing.JTextField txttipodeagua1;
    public javax.swing.JTextField txttipodecuerpodeagua;
    private javax.swing.JTextField txttipodecuerpodeagua1;
    // End of variables declaration//GEN-END:variables
}
